name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: ls
        run: ls -alh $GITHUB_WORKSPACE

      - name: update apt
        run: sudo apt-get update

      - name: install basic tools and rust
        run: sudo apt-get install -y git curl docker.io containerd runc

      - name: silent install rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Fetch the substrate node template repo
        run: git clone https://github.com/substrate-developer-hub/substrate-node-template.git

#      - name: Create the release build
#        run: |
#          cd substrate-node-template
#          cargo build --release

      - name: Setup docker config
        run: |
          echo $DOCKER_CONFIG_STRING >> ~/.docker/config
          cat ~/.docker/config
        shell: bash
        env:
          DOCKER_CONFIG_STRING: ${{secrets.DOCKER_CONFIG_STRING}}

      - name: List Empty
        run: ls -lah $GITHUB_WORKSPACE

      - name: Creates a Docker image of the template node
        run: ls -lah

      - name: Creates a Docker image of the template node
        run: |
          ls -lah
          cd substrate-node-template
          # docker build . -t t3rnsubstrate:1.0
          docker-compose up --detach

      - name: Publishes the image to a container registry (DockerHub or GHCR)
        run: |
          cd substrate-node-template
          docker tag e51494f93836 fantasticfables/t3rnsubstrate:latest
          docker push fantasticfables/t3rnsubstrate:latest

      - name: Telegram bot notifies a group of your choice
        run: echo Telegram bot notifies a group of your choice

      - name: additional steps to the pipeline for extra points
        run: echo additional steps to the pipeline for extra points
